/*
 * File: MyViewport.ui.js
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

MyViewportUi = Ext.extend(Ext.Viewport, {
    layout: 'border',
    initComponent: function() {
        this.items = [
            {
                xtype: 'panel',
                region: 'north',
                height: 40,
                border: false
            },
            {
                xtype: 'panel',
                style: 'padding:10px;',
                layout: 'fit',
                region: 'center',
                border: false,
                items: [
                    {
                        xtype: 'tabpanel',
                        activeTab: 0,
                        width: 100,
                        items: [
                            {
                                xtype: 'form',
                                title: 'Pedido Interno',
                                style: 'padding:10px;',
                                autoScroll: true,
                                items: [
                                    {
                                        xtype: 'datefield',
                                        fieldLabel: 'Label'
                                    },
                                    {
                                        xtype: 'numberfield',
                                        fieldLabel: 'Label'
                                    },
                                    {
                                        xtype: 'editorgrid',
                                        height: 310,
                                        ref: '../../../gridArticulos',
                                        columns: [
                                            {
                                                xtype: 'gridcolumn',
                                                header: 'id',
                                                dataIndex: 'id',
                                                sortable: true,
                                                width: 100,
                                                editor: {
                                                    xtype: 'textfield'
                                                }
                                            },
                                            {
                                                xtype: 'gridcolumn',
                                                header: 'nombre',
                                                dataIndex: 'nombre',
                                                sortable: true,
                                                width: 100,
                                                editor: {
                                                    xtype: 'textfield'
                                                }
                                            }
                                        ],
                                        bbar: {
                                            xtype: 'paging'
                                        }
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                title: 'Lista de pedidos'
                            },
                            {
                                xtype: 'panel',
                                title: 'Tab 2'
                            },
                            {
                                xtype: 'panel',
                                title: 'Tab 3'
                            }
                        ]
                    }
                ]
            }
        ];
        MyViewportUi.superclass.initComponent.call(this);
    }
});
