/*
 * File: MyViewport.js
 * Date: Sun Dec 23 2012 13:05:10 GMT-0700 (Hora estándar Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

MyViewport = Ext.extend(MyViewportUi, {
    initComponent: function() {
        MyViewport.superclass.initComponent.call(this);
		
		this.gridArticulos.store= new storeArticulos();
		this.gridArticulos.bottomToolbar.bind( this.gridArticulos.store );
    }
});
